### ISSUE TITLE
TODO/FIXME Count 8

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-identity#37]
- [ ] TODO: deprecate auto-retrieving capabilities, require devs to call
       Commit: (ba330d0) Update to API to use latest conventions.
       File:  [lib/index.js:773](https://github.com/digitalbazaar/bedrock-identity/blob/master/lib/index.js#L773)
       Dave Longley commented 2 years ago

  - [ ] TODO: deprecate use of `id` here?
       Commit: (ba330d0) Update to API to use latest conventions.
       File:  [lib/index.js:611](https://github.com/digitalbazaar/bedrock-identity/blob/master/lib/index.js#L611)
       Dave Longley commented 2 years ago

  - [ ] TODO: optimize with permission `and` params or something?
       Commit: (2ab0eb7) Add revocation capability.
       File:  [lib/index.js:567](https://github.com/digitalbazaar/bedrock-identity/blob/master/lib/index.js#L567)
       Dave Longley commented 2 years ago

  - [ ] FIXME remove options.fields from all libraries that call on this method
       Commit: (5a23ffa) Make fields default to undefined.
       File:  [lib/index.js:325](https://github.com/digitalbazaar/bedrock-identity/blob/master/lib/index.js#L325)
       Andrew L Jones commented 13 days ago

  - [ ] TODO: move permission check to after query to allow users with
       Commit: (ba330d0) Update to API to use latest conventions.
       File:  [lib/index.js:315](https://github.com/digitalbazaar/bedrock-identity/blob/master/lib/index.js#L315)
       Dave Longley commented 2 years ago

  - [ ] TODO: can we check `id` namespace to prevent unnecessary lookups?
       Commit: (1597c55) Fix indent.
       File:  [lib/index.js:93](https://github.com/digitalbazaar/bedrock-identity/blob/master/lib/index.js#L93)
       Dave Longley commented 2 years ago

  - [ ] TODO
       Commit: (f100ffe) Update README.
       File:  [README.md:11](https://github.com/digitalbazaar/bedrock-identity/blob/master/README.md#L11)
       David I. Lehn commented 5 years ago

  - [ ] TODO: this test is potentially odd because the identity is the
       Commit: (ba330d0) Update to API to use latest conventions.
       File:  [test/mocha/10-api.js:689](https://github.com/digitalbazaar/bedrock-identity/blob/master/test/mocha/10-api.js#L689)
       Dave Longley commented 2 years ago

**Comment by dlongley** [comment]
Closing to archive repo.
